works as depicted at README.storage \o/

diff --git a/hooks/cassandra-common b/hooks/cassandra-common
--- a/hooks/cassandra-common
+++ b/hooks/cassandra-common
@@ -25,7 +25,45 @@ am_i_the_leader () {
 bzr_ci () {
   local msg=${FUNCNAME[1]}
   test -n "$1" && msg="$1"
+  bzr st /etc/cassandra|egrep -q '^modified|added' || return 0
   bzr ci -m "[$(date "+%Y-%m-%d %H:%M:%S")] ${JUJU_UNIT_NAME}: ${msg} auto-commit" /etc/cassandra || return 0
+}
+
+# Initialize volume, mount point
+volume_init_and_mount() {
+  ## Find 1st unused device (reverse sort /dev/vdX)
+  local volid=${1:?missing volid}
+  local dev DEV=
+  local MNTPOINT=$(mnt_point_from_volid ${volid})
+  local LABEL="${volid}"
+
+  [[ -z ${MNTPOINT} ]] && return 0
+
+  for dev in $(ls -r /dev/vd?);do
+    ## Check it's not being used
+    mount | fgrep -q "${dev}" || { DEV=${dev}; break;}
+  done
+  [[ -n "${DEV}" ]] || { juju-log "ERROR: ${FUNCNAME[0]}: coult not find an unused device as /dev/vdX"; return 1;}
+
+  juju-log "INFO: ${FUNCNAME[0]}: found DEV=${DEV}"
+  [[ -b ${DEV?}  ]] || { juju-log "ERROR: ${FUNCNAME[0]}: ${DEV} is not a blockdevice"; return 1;}
+  blockdev --rereadpt ${DEV}
+  [[ -b ${DEV?}1 ]] || { sfdisk ${DEV} <<<",+," ;}
+  juju-log "INFO: ${FUNCNAME[0]}: mkfs.ext4 -L ${LABEL} ${DEV}1"
+  file -s ${DEV?}1 | egrep -q ext4 || { mkfs.ext4 -L "${LABEL}" ${DEV}1;}
+  [[ -d "${MNTPOINT}" ]] || mkdir -p "${MNTPOINT}"
+  mount | egrep -wq "${DEV}1" || mount -L "${LABEL}" "${MNTPOINT}"
+  echo "LABEL=${LABEL}    ${MNTPOINT}    auto    defaults,nobootwait,comment=${VOL_ID}" >> /etc/fstab
+  juju-log "INFO: ${FUNCNAME[0]}: $(mount | egrep -w ${DEV}1)"
+}
+
+migrate_cassandra_data_and_restart() {
+  local from=${1?} to=${2?}
+  [[ $from = $to ]] && return 0
+  /etc/init.d/cassandra stop
+  rsync -vaP "$from/" "$to/"
+  mv "$from" "$from.migrated_${JUJU_UNIT_NAME//\//-}@$(date +%s)"
+  /etc/init.d/cassandra start
 }
 
 # Install cassandra source and install packages
@@ -34,7 +72,7 @@ install_cassandra () {
   # Install the repositories
   echo "deb http://www.apache.org/dist/cassandra/debian 11x main" > /etc/apt/sources.list.d/cassandra.list
   # Add the key
-  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F758CE318D77295D
+  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4BD736A82B5C1B00
   # Update the repositories
   apt-get update
   # Ensure that cassandra does not startup before we have configured it
@@ -72,10 +110,40 @@ get_private_ip () {
   dig +short `unit-get private-address`
 }
 
+volid_config_get() {
+  local volid=$(config-get "volume-map"|python -c$'import sys;import os;from yaml import load;from itertools import chain; volume_map = load(sys.stdin)\nif volume_map: print volume_map.get(os.environ["JUJU_UNIT_NAME"])')
+  [[ $volid == None ]] && return 1
+  echo "$volid"
+}
+
+srv_root_get() {
+  sed -r -n 's,commitlog_directory: *([^ ]+)/commitlog.*,\1,p' /etc/cassandra/cassandra.yaml
+}
+mnt_point_from_volid() {
+  local volid=${1?missing volid}
+  [[ ${volid} != "" ]] && echo /srv/juju/${volid} || echo ""
+}
+srv_root_from_volid() {
+  local volid=${1?missing volid}
+  local srv_root
+  [[ ${volid} != "" ]] && echo "/srv/juju/${volid}/cassandra" || echo /var/lib/cassandra
+}
+srv_root_save() {
+  local srv_root=${1:?missing srv_root}
+  sed -i -r -e $'/data_file_directories:/{\nN;s|- /.*|- '"${srv_root}/data"'|}' \
+         -e "s|^(commitlog_directory):.*|\1: ${srv_root}/commitlog|" \
+         -e "s|^(saved_caches_directory):.*|\1: ${srv_root}/savedcache_dir|" \
+         /etc/cassandra/cassandra.yaml
+  test -d "${srv_root}" || {
+    mkdir -p "${srv_root}"
+    chown -R cassandra:cassandra "${srv_root}"
+  }
+}
+
 # Construct the cassandra.yaml file from the appropriate information above
 configure_cassandra () {
   juju-log "Configuring Cassandra"
-  local IP=$(get_private_ip)
+  local LISTEN_ADDRESS=$(get_private_ip)
   local CLUSTER_PORT=$(config-get cluster-port)
   local CLIENT_PORT=$(config-get client-port)
   local CLUSTER_NAME=$(config-get cluster-name)
@@ -83,30 +151,41 @@ configure_cassandra () {
   local HEAP_SIZE=$(config-get heap-size)
   local NEW_GEN_SIZE=$(config-get new-gen-size)
   local SRV_ROOT=$(config-get srv-root)
-  # e.g.:  /srv/cassandra/0
-  local DATA_DIR="${SRV_ROOT?}/${JUJU_UNIT_NAME}"
-  # TODO(jjo): sanity check || return 1
-
-  test -d "${DATA_DIR?}" || {
-    mkdir -p "${DATA_DIR}"
-    chown -R cassandra:cassandra "${DATA_DIR}"
-  }
+  local COMPACTION_THROUGHPUT=$(config-get compaction-throughput)
+  local DELAY_START_UNTIL_VOLUME=$(config-get delay-start-until-volume)
 
   # This needs to 'detect' whether its running in ec2
   # and use the ec2Snitch instead if it is - or we could
   # specify this as a configuration parameter
 
   # non-trivial sed to edit data_file_directories (has its value in the line following it)
-  sed -i -e "s/^cluster_name:.*/cluster_name: \'${CLUSTER_NAME}\'/" \
-         -e "s/\- seeds:.*/\- seeds: \"${IP}\"/" \
-         -e "s/^storage_port:.*/storage_port: ${CLUSTER_PORT}/" \
-         -e "s/^listen_address:.*/listen_address: ${IP}/" \
-         -e "s/^rpc_address:.*/rpc_address: ${IP}/" \
-         -e "s/^rpc_port:.*/rpc_port: ${CLIENT_PORT}/" \
-         -e $'/data_file_directories:/{\nN;s|- /.*|- '"${DATA_DIR}/data"'|}' \
-         -e "s|^commitlog_directory:.*|commitlog_directory: ${DATA_DIR}/commitlog|" \
-         -e "s|^saved_caches_directory:.*|saved_caches_directory: ${DATA_DIR}/savedcache_dir|" \
+  sed -i -r -e "s/^cluster_name:.*/cluster_name: \'${CLUSTER_NAME}\'/" \
+         -e "s/(- seeds):.*/\1: \"${LISTEN_ADDRESS}\"/" \
+         -e "s/^(storage_port):.*/\1: ${CLUSTER_PORT}/" \
+         -e "s/^(listen_address):.*/\1: ${LISTEN_ADDRESS}/" \
+         -e "s/^(rpc_address):.*/\1: ${LISTEN_ADDRESS}/" \
+         -e "s/^(rpc_port):.*/\1: ${CLIENT_PORT}/" \
+         -e "s/^(compaction_throughput_mb_per_sec):.*/\1: ${COMPACTION_THROUGHPUT}/" \
          /etc/cassandra/cassandra.yaml
+
+  local volid=$(volid_config_get)
+### TODO(jjo): DELAY_START_UNTIL_VOLUME logic/state-transition needs fixing
+#  if [[ $DELAY_START_UNTIL_VOLUME = True && -z ${volid} ]];then
+#    echo 'test start == "$1" && exit 0' > /etc/default/cassandra
+#  else
+#    echo '##NEEDS_START' > /etc/default/cassandra
+#  fi
+  local srv_root_curr=$(srv_root_get)
+  [[ -n "${volid}" ]] && {
+    local srv_root_new=$(srv_root_from_volid ${volid})
+    [[ ${srv_root_new} != ${srv_root_curr} ]] && {
+      volume_init_and_mount ${volid}
+      [[ -d ${srv_root_curr}/data ]] && \
+        migrate_cassandra_data_and_restart ${srv_root_curr} ${srv_root_new}
+      srv_root_save ${srv_root_new}
+    }
+  }
+
   # Open port ready for expose
   open-port ${CLIENT_PORT}/TCP
 
@@ -124,6 +203,11 @@ configure_cassandra () {
 
 # Service Control Commands
 restart_cassandra () {
+  grep -q NEEDS_START /etc/default/cassandra && {
+    echo '' > /etc/default/cassandra
+    service cassandra start
+    return $?
+  }
   juju-log "Restarting Cassandra"
   service cassandra status && service cassandra restart || :
 }
@@ -203,6 +287,8 @@ decommission_node () {
 
 # Actual processing
 COMMAND=${0##*/}
+
+export BZR_HOME=/root
 
 case $COMMAND in
   install)
