Add exec.d support.

diff --git a/hooks/cassandra-common b/hooks/cassandra-common
--- a/hooks/cassandra-common
+++ b/hooks/cassandra-common
@@ -1,5 +1,19 @@
 #!/bin/bash
 # vim: set tabstop=2 expandtab:
+
+# Pre-exec
+if [[ -d exec.d ]]; then
+    shopt -s nullglob
+    for f in exec.d/*/charm-pre-install; do
+    [[ -x "$f" ]] || continue
+    ${SHELL} -c "$f"|| {
+        ## bail out if anyone fails
+        juju-log -l ERROR "$f: returned exit_status=$? "
+        exit 1
+    }
+    done
+fi
+
 . ./scripts/volume-common.sh
 
 set -e
