added scripts/immutable-common.sh , still no-op

diff --git a/hooks/cassandra-common b/hooks/cassandra-common
--- a/hooks/cassandra-common
+++ b/hooks/cassandra-common
@@ -1,6 +1,7 @@
 #!/bin/bash
 # vim: set tabstop=2 expandtab:
 . ./scripts/volume-common.sh
+. ./scripts/immutable-common.sh
 
 set -e
 
@@ -49,15 +50,7 @@ install_cassandra () {
   # Update the repositories
   apt-get update
   # Ensure that cassandra does not startup before we have configured it
-  cat > /usr/sbin/policy-rc.d <<EOF
-#!/bin/bash
-if [ "\$1" == "cassandra" ] && [ "\$2" == "start" ]; then
-        exit 101
-else
-        exit 0
-fi
-EOF
-  chmod a+x /usr/sbin/policy-rc.d
+  disable_cassandra_start
   # Install the package
   apt-get -qq install -y cassandra python-cheetah dnsutils
   bzr_ci
@@ -103,10 +96,15 @@ srv_root_save() {
   }
 }
 disable_cassandra_start() {
-  echo '[ start = "$1" ] && exit 0' > /etc/default/cassandra
-}
+  cat > /usr/sbin/policy-rc.d <<EOF
+#!/bin/bash
+[[ "$1"-"$2" == cassandra-start ]] && exit 101
+exit 0
+EOF
+  chmod a+x /usr/sbin/policy-rc.d
+  }
 enable_cassandra_start() {
-  echo '## NEEDS_START' > /etc/default/cassandra
+  rm -f /usr/sbin/policy-rc.d
 }
 
 # Construct the cassandra.yaml file from the appropriate information above
@@ -143,11 +141,13 @@ configure_cassandra () {
   else
     disable_cassandra_start
     juju-log "ERROR: invalid storage_config at ${FUNCNAME[0]}"
+    return 1
   fi
   local srv_root_curr=$(srv_root_get)
   (
   set -e
   if [[ -n ${volid} && ${volid} != --ephermeral ]];then
+    #immutable_set "volid" "$volid" || return 1
     local srv_root_new=$(srv_root_from_volid ${volid})
     if ${srv_root_new} != ${srv_root_curr} ]];then
       :
@@ -179,6 +179,7 @@ configure_cassandra () {
 
 # Service Control Commands
 restart_cassandra () {
+  ## TODO(jjo): NEEDS_START logic
   grep -q NEEDS_START /etc/default/cassandra && {
     echo '' > /etc/default/cassandra
     service cassandra start
@@ -268,6 +269,7 @@ export BZR_HOME=/root
 
 case $COMMAND in
   install)
+    #immutable_cleanup
     # Install cassandra first run only
     [[ -d /usr/share/cassandra ]] || install_cassandra
     # Initialize /etc/cassandra bzr
